server:
  port: 8662
spring:
  application:
    name: gateway-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    resource-service:
      path: /resource/**
      serviceId: resource-service
      stripPrefix: true
    user-service:
      path: /user/**
      serviceId: user-service
      stripPrefix: true
